# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: mantiby/openchain:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run linting and metrics
          command: |
            . venv/bin/activate
            flake8 --output-file flake8-report

          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -s openchain/tests/ -p '*_tests.py'

          name: run coverage
          command: |
            . venv/bin/activate
            coverage run -m unittest discover -s openchain/tests/ -p '*_tests.py'
            coverage report --fail-under=75 -m > coverage-report

      - store_artifacts:
          path: flake8-report

      - store_artifacts:
          path: coverage-report
